services:
  - type: web
    name: kintone-chatbot-saas
    env: docker
    plan: free
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: ENCRYPTION_KEY
        sync: false
      - key: ALLOWED_ORIGINS
        value: "*"
      - key: DATABASE_URL
        value: "sqlite:////data/data.db"